### ISSUE TITLE
LD_LIBRARY_PATH and sudo

### ISSUE THREAD

**Issue by srenatus** [iquiw/ghc-NetBSD-patches#2]
Hi there, thanks for your work on this.

Just a detail on the [website](http://www.hahakigi.net/ghc), the `sudo gmake install` step won't work if option (b) was chosen for `LD_LIBRARY_PATH`, since `sudo` (and `sudo -E`, strangely, too) strips the environment.  A workaround is `sudo LD_LIBRARY_PATH=$LD_LIBRARY_PATH gmake install`.

I don't suppose updating the docs is critical, I'll just leave this here for other people to stumble upon.

Cheers
Stephan

**Comment by iquiw** [comment]
Thank you for correcting it.
I will update the step.

**Comment by iquiw** [comment]
Done.
